Development
SemicolonExpected/TaskManager pull request #44
Opened 2020-10-23 17:50 UTC by deusalexmachina

Merging dev branch into master before code diverges too much. Can someone review? this appears to work with meghana's task routes. Thanks!

2020-10-23 17:50 UTC, pep8speaks commented
Hello @deusalexmachina! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`run_tests.py`](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/run_tests.py):

> [Line 6:22](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/run_tests.py#L6): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`task_manager/Model/task.py`](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/Model/task.py):

> [Line 15:1](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/Model/task.py#L15): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 34:4](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/Model/task.py#L34): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file











* In the file [`task_manager/tests/test_task.py`](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_task.py):

> [Line 10:23](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_task.py#L10): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:23](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_task.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 16:23](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_task.py#L16): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 19:23](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_task.py#L19): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`task_manager/tests/test_user.py`](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_user.py):

> [Line 21:21](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_user.py#L21): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 21:21](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_user.py#L21): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 21:21](https://github.com/SemicolonExpected/TaskManager/blob/5812866606dbc3717548725fa15fa512efa1fa89/task_manager/tests/test_user.py#L21): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-10-23 17:53 UTC, SemicolonExpected requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-23 17:53 UTC, SemicolonExpected commented on task_manager/api.py
> +from flask_restx import Resource, Namespace
F811: redefinition of unused 'Resource' from line 6  <!-- Automatically posted by Lintly -->

2020-10-23 18:35 UTC, SemicolonExpected commented
Why did you change the keys from an env variable to a string?

2020-10-23 20:31 UTC, deusalexmachina commented
> Why did you change the keys from an env variable to a string?

We should have a consistent secret key for when we test login and sessions, otherwise we will have issues when someone tries to decrypt something that was encoded using someone else's local variable. We can generate a new server-side key when we are finished.

2020-10-24 02:04 UTC, SemicolonExpected commented
>  We can generate a new server-side key when we are finished.

I'm a bit confused since even after we're finished in theory it would still be worked on. Wouldn't it make more sense to have 2, one for testing (that you use a github secret for) and one that you set in a .env that is passed around for people to play with?

2020-10-24 02:46 UTC, deusalexmachina commented
> I'm a bit confused since even after we're finished in theory it would still be worked on. Wouldn't it make more sense to have 2, one for testing (that you use a github secret for) and one that you set in a .env that is passed around for people to play with?

We do in essence have two options. the secret_key is for dev production. and uncommenting a line allows us to load from .env

2020-10-24 02:49 UTC, SemicolonExpected commented
I guess my question is more of should we not also save the plantext key in the env file and just switch it out (via comment/uncomment) when we switch from dev to prod built? Just in case we have to use it elsewhere

2020-10-24 14:33 UTC, deusalexmachina commented
> I guess my question is more of should we not also save the plantext key in the env file and just switch it out (via comment/uncomment) when we switch from dev to prod built? Just in case we have to use it elsewhere

I added a new commit, default loads from .env, running in dev replaces with the test key.

2020-10-24 22:37 UTC, merged